### ISSUE TITLE
Choose your own (fancy nick etc) screensaver

### ISSUE THREAD

**Issue by annejan** [SHA2017-badge/micropython-esp32#110]
Related to #96

It would be really nice if users could choose what they want on the screen before splash goes to deepsleep . .

**Comment by Roosted7** [comment]
Will be handled by boot.py

**Comment by Roosted7** [comment]
Fixed

**Comment by Roosted7** [comment]
In nvs page 'badge' the key 'boot.splash' changes the default splash.
If you want to draw over the existing splash that is possible with a service
