### ISSUE TITLE
rtcmem: check if offset is valid

### ISSUE THREAD

**Issue by basvs** [SHA2017-badge/micropython-esp32#111]

**Comment by basvs** [comment]
#define RTC_SLOW_MEM ((uint32_t*) 0x50000000)       /*!< RTC slow memory, 8k size */

I guess we can use indexes 0…2047 then..

**Comment by Roosted7** [comment]
Uhmm on the badge it only works until index 255

**Comment by annejan** [comment]
yah, afaik we limited this to 1K bytes . .

**Comment by basvs** [comment]
(/micropython/esp32/esprtcmem.h)
#define USER_RTC_MEM_SIZE 256

(/micropython/esp32/esprtcmem.c)
static uint8_t RTC_DATA_ATTR rtcmemcontents[USER_RTC_MEM_SIZE] = {0};
