### ISSUE TITLE
Put peripherals to sleep on deepsleep

### ISSUE THREAD

**Issue by annejan** [SHA2017-badge/micropython-esp32#114]
This includes:

* LEDs
* SDcard
* E-ink

**Comment by basvs** [comment]
LEDs / SDcard → we can disable the power to the LEDs/SDcard.
    (use both badge_power_leds_disable() and badge_power_sdcard_disable())

E-ink →call badge_eink_deep_sleep()

**Comment by Roosted7** [comment]
@basvs Can you make those API's available to python? I think I should be able to manage that as well, but I know it costs you a fraction of that time :)

**Comment by basvs** [comment]
will have a look at it

**Comment by basvs** [comment]
pr #151 contains the hooks for the led and sdcard.

**Comment by basvs** [comment]
pr #153 contains the hooks for the eink deep sleep

**Comment by basvs** [comment]
@Roosted7 the api's are merged

**Comment by sebastius** [comment]
So, is this one done?

**Comment by annejan** [comment]
@Roosted7 / @rnplus are these now called on deepsleep?

Should they be added to deespleep.py ?

**Comment by Roosted7** [comment]
Done
Awesome work @basvs
