### ISSUE TITLE
boot.py not update-able via OTA

### ISSUE THREAD

**Issue by Roosted7** [SHA2017-badge/micropython-esp32#115]
boot.py should have a version, so that it can be updated with ota

**Comment by sebastius** [comment]
Sounds fairly dangerous to implement. If OTA is compromised... Oh wait, then we're screwed anyway. 

However: if it is writable then you open the risk of having apps modify it. 

Attack suggestion:

Generic fun game that also packs a 'service' that does 'things' to boot.py. 

So this is a no for me.
