### ISSUE TITLE
open() does not allow binary IO

### ISSUE THREAD

**Issue by polyfloyd** [SHA2017-badge/micropython-esp32#146]
Reading files opened by open("rb") returns a TextIOWrapper instead of something that allows binary IO. The emulator returns an instance of FileIO which seems to work just fine.
```python
with open("somefile", "rb") as f:
    print(type(f)) # TextIOWrapper, expected be FileIO (or BufferedReader according to the Python documentation)
```

As a consequence, `f.read()` returns a `str` instead of `bytes`.

**Comment by basvs** [comment]
hmm.. it should return FileIO.. diving into it..

**Comment by basvs** [comment]
probably fixed in pull-request #166

**Comment by annejan** [comment]
@polyfloyd can you verify if current `master` solves this issue for you?

**Comment by polyfloyd** [comment]
@annejan Yeah, it has.
