### ISSUE TITLE
Leaving badge in launcher or installer accidentally drains battery fast

### ISSUE THREAD

**Issue by Roosted7** [SHA2017-badge/micropython-esp32#148]
I think there should be a auto return to home if someone forgets his/hers/something badge in a battery consuming state and does not give any inputs for a couple of minutes

Yes this happened to myself...

**Comment by sebastius** [comment]
well you could have it go into deep-sleep after 1 minute with the bits set to return to the launcher, right?

**Comment by annejan** [comment]
I don't think we should protect people from their own stupidity (apps can drain battery, not an issue in my opinion).

**Comment by Roosted7** [comment]
Fixed a while ago
