### ISSUE TITLE
When waking up from touch interrupt, the information about the touch event is lost

### ISSUE THREAD

**Issue by Roosted7** [SHA2017-badge/micropython-esp32#154]
We would be able to implement very transparent sleeping in some places if we would be able to read which input triggered the interrupt. I think this is possible by not resetting the MPR121 on every python boot..?

Could we extend reset_cause() or implement something for wakeup_cause() ?

**Comment by Roosted7** [comment]
Another way of implementing would be to be able set a interrupt bitmask in the MPR121, is that feasonable?

**Comment by basvs** [comment]
As far as I know, you cannot find out which button triggered the wake-up. The button is already released, so the status register will not show any pressed buttons. The mpr121 also doesn't support an interrupt bitmask. It's all or nothing.

**Comment by sebastius** [comment]
Impossible with this chip.

**Comment by Roosted7** [comment]
Let's keep this open @sebastius.
I would love to use the ULP for this

**Comment by basvs** [comment]
We have to use the I2C to access this. It might be possible, but that isn't easy to implement.

**Comment by annejan** [comment]
ULP doesn't seem to be powerful enough for this from what I have been reading . .

**Comment by basvs** [comment]
@Roosted7 can we close this?
