### ISSUE TITLE
nvs_[get/set]_u[8/16] not working

### ISSUE THREAD

**Issue by Roosted7** [SHA2017-badge/micropython-esp32#93]
Nice to store ints in the NVS, but current code just crashes

**Comment by annejan** [comment]
Can't reproduce . .

**Comment by Roosted7** [comment]
Okay, if memory serves me well tsd also had this issue.
(His badge crashed before he reverted renze his commit that started using int instead of str)

**Comment by annejan** [comment]
Ah, might it be that the values are stored as string, but attempt to retrieve as int? 

That would make it a legacy data issue.

**Comment by Roosted7** [comment]
Ah could be.. My badge crashes when trying the get or set the voltage levels for the battery(bar)

**Comment by basvs** [comment]
I also got crashes when i requested unset entries. I will dive into this

**Comment by basvs** [comment]
>>> badge.nvs_get_u8("lalala", "lala", 42)
42
>>> badge.nvs_get_u8("lalala", "lala")
Guru Meditation Error of type LoadProhibited occurred on core  0. Exception was unhandled.

**Comment by basvs** [comment]
The code works when you use a default. If not, you will get a null-pointer-exception.

I have a patch ready.

**Comment by basvs** [comment]
We cannot merge this yet. It triggers bugs in other scripts. Have to fix that first.. :)

**Comment by basvs** [comment]
scripts are fixed; code is merged.
